### ISSUE TITLE
[Bug]: syntax error in the `feature_request.yml`

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/.github#1]
### Describe the bug

There is a syntax error in the feature_request.yml. 

### Describe how to reproduce the bug

See error message [here](https://github.com/NOAA-FIMS/.github/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml): 

YAML syntax error: (): could not find expected ':' while scanning a simple key at line 45 column 7. 

### Screenshots

![image](https://github.com/NOAA-FIMS/.github/assets/59936250/f1344b15-ac43-4659-afb2-c95a0ccce851)

### Which OS are you seeing the problem on?

Windows

### Which browser are you seeing the problem on?

Chrome

**Comment by kellijohnson-NOAA** [comment]
Fixed, along with other formatting errors with [c896d84](https://github.com/NOAA-FIMS/.github/commit/c896d84767e03d30a252ba9879619ab3e8b45a4f).
