### ISSUE TITLE
[Bug]: labels are not automatically added to published issues

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [NOAA-FIMS/.github#2]
### Describe the bug

The labels `kind: bug` and `status: triage_needed` don't automatically appear on the published bug report [here](https://github.com/NOAA-FIMS/.github/issues/1). 

### Describe how to reproduce the bug
We might need to update the label `bug` to `kind: bug`  and add a lable of `triage_needed`. See [examples](https://github.com/NOAA-FIMS/FIMS/labels) from the FIMS repo.
There is a potential syntax issue in the [title](https://github.com/NOAA-FIMS/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L3) of the 'bug_report.yml`. Maybe use [Bug]: instead of [Bug:]?

### Which OS are you seeing the problem on?

Windows

### Which browser are you seeing the problem on?

Chrome

**Comment by kellijohnson-NOAA** [comment]
Thanks @Bai-Li-NOAA and I believe that is happening because those labels are not in this repository. My next task is to create organization-wide labels. I think that will fix this problem.

**Comment by kellijohnson-NOAA** [comment]
Organization-wide labels have been standardized. Now, new repositories will automatically adopt the FIMS labels instead of the default GitHub labels. This did not correct current repositories so I went through .github, collaborative_workflow, FIMS, and seaside-chats and updated all the labels.
